<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-LKUJ5DI" ignored="0" name="RetryMultipleFailedTests" tests="9" failures="2" timestamp="25 Aug 2019 11:28:28 GMT" time="0.089" errors="0">
  <testcase name="Test1" time="0.009" classname="retryLogic.retryFailedTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="retryLogic.retryFailedTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="retryLogic.retryFailedTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="retryLogic.retryFailedTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at retryLogic.retryFailedTest.Test1(retryFailedTest.java:15)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.002" classname="retryLogic.retryFailedTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="retryLogic.retryFailedTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="retryLogic.retryFailedTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="retryLogic.retryFailedTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at retryLogic.retryFailedTest.Test2(retryFailedTest.java:23)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.001" classname="retryLogic.retryFailedTest"/>
</testsuite> <!-- RetryMultipleFailedTests -->
